# This file adds various things I think should be in the standard dfhack.init

# TwbT multilevel view
multilevel 5

# add fertility indicator to nestboxes
tweak eggs-fertile

# log extra stuff for Soundsense
soundsense

# Lethosor's scripts are part of DFHack, but not activated due to submodule issues
keybinding add Alt-S@title settings-manager
keybinding add Alt-S@dwarfmode/Default settings-manager
embark-tools enable sticky
gui/extended-status enable
